module.exports = {
  alps: require("./alps"),
  button: require("./button"),
  choc: require("./choc"),
  chocmini: require("./chocmini"),
  diode: require("./diode"),
  jstph: require("./jstph"),
  jumper: require("./jumper"),
  mx: require("./mx"),
  oled: require("./oled"),
  omron: require("./omron"),
  pad: require("./pad"),
  promicro: require("./promicro"),
  resetButton: require("./resetButton"),
  rgb: require("./rgb"),
  rotary: require("./rotary"),
  scrollwheel: require("./scrollwheel"),
  slider: require("./slider"),
  switch: require("./switch"),
  trrs: require("./trrs"),
  via: require("./via"),
};
