manifest:
  remotes:
    - name: unit01
      url-base: https://github.com/jasepellerin
  projects:
    - name: zmk
      remote: jasepellerin
      revision: main
      import: app/west.yml
  self:
    path: config
