file_format: "1"
id: unit01
name: Unit 01
type: shield
url: https://github.com/jasepellerin/zmk-config
requires: [pro_micro]
exposes: [i2c_oled]
features:
  - keys
siblings:
  - unit01_left
  - unit01_right
